### ISSUE TITLE
Getting Error when running batch.py --dewarp

### ISSUE THREAD

**Issue by aishmittal** [phulin/rebook#14]
**Command:**
```python batch.py --dewarp -f FILE_NAME.jpg```

**Error:**
detected dpi: 200
AH = 25
overall: mean: 6.957979429464889 std: 1.433384350862489
C:\ProgramData\Anaconda3\lib\site-packages\numpy\polynomial\_polybase.py:798: RankWarning: The fit may be poorly conditioned
  res = cls._fit(xnew, y, deg, w=w, rcond=rcond, full=full)
original lines: 112 merged lines: 112
Bimodal! Splitting page!
split: 32 out of 112 @ 3073
==== PAGE 0 ====
Traceback (most recent call last):
  File "batch.py", line 218, in <module>
    run(args)
  File "batch.py", line 154, in run
    _, out_images = process_image(im, dpi=args.dpi)
  File "batch.py", line 43, in process_image
    dewarped_images = dewarp.kim2014(original_rot90)
  File "C:\Users\aimittal\Desktop\Enhanced Copy\rebook\rebook\dewarp.py", line 1044, in kim2014
    page_image = page_crop.apply(orig)
  File "C:\Users\aimittal\Desktop\Enhanced Copy\rebook\rebook\geometry.py", line 225, in apply
    return im[crop.y0:crop.y1, crop.x0:crop.x1]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by aishmittal** [comment]
Found a fix for this:
replaced 
```return im[crop.y0:crop.y1, crop.x0:crop.x1]```
with
```return im[int(crop.y0):int(crop.y1), int(crop.x0):int(crop.x1)]```
